// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCJmDsuwJOnwCjn53cKbgSlroo5BVCC4',
    appId: '1:223861047139:web:b2a37c3b8e45b760965d56',
    messagingSenderId: '223861047139',
    projectId: 'flutter-notifications-8b447',
    authDomain: 'flutter-notifications-8b447.firebaseapp.com',
    storageBucket: 'flutter-notifications-8b447.appspot.com',
    measurementId: 'G-0HC1J5SMER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3_iGY4-FQStfZIXFXcdwcE4dQ-4_qGg',
    appId: '1:223861047139:android:81e422c6d25aec7f965d56',
    messagingSenderId: '223861047139',
    projectId: 'flutter-notifications-8b447',
    storageBucket: 'flutter-notifications-8b447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjTR2H-V3ObqUzEiURPtqhQ1HvWDvrDMs',
    appId: '1:223861047139:ios:fbdf3fc2bd3d84f7965d56',
    messagingSenderId: '223861047139',
    projectId: 'flutter-notifications-8b447',
    storageBucket: 'flutter-notifications-8b447.appspot.com',
    iosClientId:
        '223861047139-vurgrupq0lucnfk65n4otmdeju7t939q.apps.googleusercontent.com',
    iosBundleId: 'com.notifs.psv',
  );
}
